:load ../src/Ascii.scala

//  Michael's slide
ASCII HEIGHT 20
ASCII WIDTH 30

ASCII CHANGE_COLOR CYAN
ASCII MOVE RIGHT
ASCII MOVE DOWN THEN RIGHT
ASCII ROTATE NINETY

//  Amro's slide
ASCII MOVE DOWN THEN RIGHT DO WHILE EXISTS DOWN AND RIGHT END