:load src/ASCII.scala

ASCII HEIGHT 25
ASCII WIDTH 80

ASCII SELECT_RECT (79,4) FILL RED
ASCII JUMP (4, 0)
ASCII SELECT_RECT (79,4) FILL MAGENTA
ASCII JUMP (8, 0)
ASCII SELECT_RECT(79, 4) FILL YELLOW
ASCII JUMP (12, 0)
ASCII SELECT_RECT(79, 4) FILL GREEN
ASCII JUMP (16, 0)
ASCII SELECT_RECT(79, 4) FILL CYAN
ASCII JUMP (20, 0)
ASCII SELECT_RECT(79, 4) FILL BLUE
ASCII RENDER
