:load ../src/Ascii.scala

ASCII JUMP (5, 5)
ASCII RECT (5, 5)
ASCII RENDER
ASCII SELECT_RECT (5, 5) MOVE RIGHT THEN DOWN
ASCII RENDER
ASCII MOVE UP THEN LEFT
ASCII SELECT_RECT (7, 7) FILL 'x' THEN MOVE RIGHT THEN DOWN
ASCII RENDER