:load src/ASCII.scala

ASCII HEIGHT 20
ASCII WIDTH 50
ASCII CHANGE_COLOR BLACK

ASCII MOVE RIGHT DO 22 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 6 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (1, 0)
ASCII SET

ASCII MOVE RIGHT DO 16 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 18 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (2, 0)
ASCII SET

ASCII MOVE RIGHT DO 13 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 24 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (3, 0)
ASCII SET

ASCII MOVE RIGHT DO 10 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 30 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (4, 0)
ASCII SET

ASCII MOVE RIGHT DO 8 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 34 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (5, 0)
ASCII SET

ASCII MOVE RIGHT DO 6 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 38 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (6, 0)
ASCII SET

ASCII MOVE RIGHT DO 3 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 44 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (7, 0)
ASCII SET

ASCII MOVE RIGHT DO 2 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 46 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (8, 0)
ASCII SET

ASCII MOVE RIGHT
ASCII UNSET
ASCII MOVE RIGHT DO 48 TIMES
ASCII SET
ASCII MOVE RIGHT
ASCII MOVE LEFT
ASCII JUMP (11, 0)
ASCII SET

ASCII MOVE RIGHT
ASCII UNSET
ASCII MOVE RIGHT DO 48 TIMES
ASCII SET
ASCII MOVE RIGHT
ASCII MOVE LEFT
ASCII JUMP (12, 0)
ASCII SET

ASCII MOVE RIGHT DO 2 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 46 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (13, 0)
ASCII SET

ASCII MOVE RIGHT DO 3 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 44 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (14, 0)
ASCII SET

ASCII MOVE RIGHT DO 6 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 38 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (15, 0)
ASCII SET

ASCII MOVE RIGHT DO 8 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 34 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (16, 0)
ASCII SET

ASCII MOVE RIGHT DO 10 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 30 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (17, 0)
ASCII SET

ASCII MOVE RIGHT DO 13 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 24 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (18, 0)
ASCII SET

ASCII MOVE RIGHT DO 16 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 18 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT
ASCII JUMP (19, 0)
ASCII SET

ASCII MOVE RIGHT DO 22 TIMES
ASCII UNSET
ASCII MOVE RIGHT DO 6 TIMES
ASCII SET
ASCII MOVE RIGHT DO WHILE EXISTS RIGHT END
ASCII MOVE LEFT


ASCII JUMP (4, 13)
ASCII SELECT_RECT (5,4) FILL BLACK

ASCII JUMP (4, 31)
ASCII SELECT_RECT (5,4) FILL BLACK

ASCII JUMP (13, 20)
ASCII SELECT_RECT (10, 2) FILL BLACK

ASCII JUMP (13, 16)
ASCII MOVE RIGHT
ASCII SELECT_RECT (2, 1) FILL BLACK

ASCII JUMP (13, 31)
ASCII SELECT_RECT (2, 1) FILL BLACK

ASCII JUMP (13, 34)
ASCII MOVE RIGHT



ASCII JUMP (0,0)

ASCII RENDER
