ASCII WIDTH 175
ASCII HEIGHT 30
ASCII UNSET
ASCII CHANGE_COLOR CYAN
ASCII MOVE RIGHT DO 20 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII SET
ASCII MOVE LEFT DO 10 TIMES
ASCII MOVE RIGHT DO 5 TIMES
ASCII MOVE DOWN DO 11 TIMES

ASCII UNSET
ASCII MOVE UP DO 11 TIMES
ASCII MOVE RIGHT DO 13 TIMES

ASCII SET
ASCII MOVE DOWN DO 10 TIMES
ASCII MOVE UP DO 5 TIMES
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII MOVE UP DO 10 TIMES
ASCII MOVE RIGHT

ASCII UNSET
ASCII MOVE RIGHT DO 4 TIMES

ASCII SET
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE LEFT DO 10 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE LEFT DO 10 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII MOVE RIGHT DO 11 TIMES

ASCII UNSET
ASCII MOVE RIGHT DO 20 TIMES
ASCII MOVE UP DO 10 TIMES

ASCII SET
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE LEFT DO 10 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE LEFT DO 10 TIMES
ASCII MOVE DOWN DO 5 TIMES
ASCII MOVE RIGHT DO 11 TIMES

ASCII UNSET
ASCII MOVE RIGHT DO 10 TIMES
ASCII MOVE UP DO 10 TIMES

ASCII SET
ASCII MOVE DOWN DO 10 TIMES
ASCII MOVE UP DO 10 TIMES
ASCII MOVE DOWN THEN RIGHT DO 10 TIMES
ASCII MOVE UP DO 11 TIMES

ASCII UNSET
ASCII MOVE DOWN
ASCII MOVE RIGHT DO 10 TIMES

ASCII SET
ASCII MOVE DOWN DO 10 TIMES
ASCII MOVE RIGHT THEN RIGHT THEN UP DO 5 TIMES
ASCII MOVE LEFT THEN LEFT THEN UP DO 5 TIMES
ASCII MOVE UP
 

ASCII RENDER
